from tkinter import *  
parent = Tk()  
red = Button(parent, text = "Red", fg = "red")  
red.pack( side = LEFT) 
greenbutton = Button(parent, text = "Black", fg = "black",size=50)  
greenbutton.pack( side = RIGHT )  
bluebutton = Button(parent, text = "Blue", fg = "blue")  
bluebutton.pack( side = TOP )  
blackbutton = Button(parent, text = "Green", fg = "green")  
blackbutton.pack( side = BOTTOM)  
parent.mainloop()  
